### ISSUE TITLE
Freeze at 10% loading after injecting the base

### ISSUE THREAD

**Issue by BlumeCoding** [2much4u/PS4-GTA-V-Menu-Base#3]
EU GTA 5 frezzing game at 10% loading

**Comment by ghost** [comment]
Try using a real installation of linux instead of a virtual. Solved this problem for me...

**Comment by BlumeCoding** [comment]
FOR ME NOT

**Comment by BlumeCoding** [comment]
FIXED I USED WINDOWS 10 linux distrubiton no errors it has really todo with the virtual image i think
